// Bảng dịch tên quốc gia từ tiếng Anh sang tiếng Việt
export const COUNTRY_NAMES_VI = {
  // Châu Á
  Vietnam: 'Việt Nam',
  China: 'Trung Quốc',
  Japan: 'Nhật Bản',
  'South Korea': 'Hàn Quốc',
  'North Korea': 'Triều Tiên',
  Thailand: 'Thái Lan',
  Singapore: 'Singapore',
  Malaysia: 'Malaysia',
  Indonesia: 'Indonesia',
  Philippines: 'Philippines',
  Cambodia: 'Campuchia',
  Laos: 'Lào',
  Myanmar: 'Myanmar',
  India: 'Ấn Độ',
  Pakistan: 'Pakistan',
  Bangladesh: 'Bangladesh',
  'Sri Lanka': 'Sri Lanka',
  Nepal: 'Nepal',
  Bhutan: 'Bhutan',
  Afghanistan: 'Afghanistan',
  Iran: 'Iran',
  Iraq: 'Iraq',
  'Saudi Arabia': 'Ả Rập Saudi',
  'United Arab Emirates': 'Các Tiểu vương quốc Ả Rập Thống nhất',
  Qatar: 'Qatar',
  Kuwait: 'Kuwait',
  Bahrain: 'Bahrain',
  Oman: 'Oman',
  Yemen: 'Yemen',
  Syria: 'Syria',
  Lebanon: 'Lebanon',
  Jordan: 'Jordan',
  Israel: 'Israel',
  Palestine: 'Palestine',
  Turkey: 'Thổ Nhĩ Kỳ',
  Cyprus: 'Síp',
  Georgia: 'Georgia',
  Armenia: 'Armenia',
  Azerbaijan: 'Azerbaijan',
  Kazakhstan: 'Kazakhstan',
  Uzbekistan: 'Uzbekistan',
  Turkmenistan: 'Turkmenistan',
  Kyrgyzstan: 'Kyrgyzstan',
  Tajikistan: 'Tajikistan',
  Mongolia: 'Mông Cổ',
  Brunei: 'Brunei',
  'Timor-Leste': 'Đông Timor',
  Maldives: 'Maldives',

  // Châu Âu
  'United Kingdom': 'Vương quốc Anh',
  France: 'Pháp',
  Germany: 'Đức',
  Italy: 'Ý',
  Spain: 'Tây Ban Nha',
  Portugal: 'Bồ Đào Nha',
  Netherlands: 'Hà Lan',
  Belgium: 'Bỉ',
  Luxembourg: 'Luxembourg',
  Switzerland: 'Thụy Sĩ',
  Austria: 'Áo',
  Poland: 'Ba Lan',
  'Czech Republic': 'Cộng hòa Séc',
  Slovakia: 'Slovakia',
  Hungary: 'Hungary',
  Slovenia: 'Slovenia',
  Croatia: 'Croatia',
  'Bosnia and Herzegovina': 'Bosnia và Herzegovina',
  Serbia: 'Serbia',
  Montenegro: 'Montenegro',
  'North Macedonia': 'Bắc Macedonia',
  Albania: 'Albania',
  Greece: 'Hy Lạp',
  Bulgaria: 'Bulgaria',
  Romania: 'Romania',
  Moldova: 'Moldova',
  Ukraine: 'Ukraine',
  Belarus: 'Belarus',
  Russia: 'Nga',
  Lithuania: 'Lithuania',
  Latvia: 'Latvia',
  Estonia: 'Estonia',
  Finland: 'Phần Lan',
  Sweden: 'Thụy Điển',
  Norway: 'Na Uy',
  Denmark: 'Đan Mạch',
  Iceland: 'Iceland',
  Ireland: 'Ireland',
  Malta: 'Malta',
  Monaco: 'Monaco',
  Andorra: 'Andorra',
  'San Marino': 'San Marino',
  'Vatican City': 'Vatican',
  Liechtenstein: 'Liechtenstein',

  // Châu Mỹ
  'United States': 'Hoa Kỳ',
  Canada: 'Canada',
  Mexico: 'Mexico',
  Guatemala: 'Guatemala',
  Belize: 'Belize',
  'El Salvador': 'El Salvador',
  Honduras: 'Honduras',
  Nicaragua: 'Nicaragua',
  'Costa Rica': 'Costa Rica',
  Panama: 'Panama',
  Cuba: 'Cuba',
  Jamaica: 'Jamaica',
  Haiti: 'Haiti',
  'Dominican Republic': 'Cộng hòa Dominica',
  'Puerto Rico': 'Puerto Rico',
  'Trinidad and Tobago': 'Trinidad và Tobago',
  Barbados: 'Barbados',
  'Saint Lucia': 'Saint Lucia',
  Grenada: 'Grenada',
  'Saint Vincent and the Grenadines': 'Saint Vincent và Grenadines',
  'Antigua and Barbuda': 'Antigua và Barbuda',
  Dominica: 'Dominica',
  'Saint Kitts and Nevis': 'Saint Kitts và Nevis',
  Bahamas: 'Bahamas',
  Brazil: 'Brazil',
  Argentina: 'Argentina',
  Chile: 'Chile',
  Peru: 'Peru',
  Colombia: 'Colombia',
  Venezuela: 'Venezuela',
  Ecuador: 'Ecuador',
  Bolivia: 'Bolivia',
  Paraguay: 'Paraguay',
  Uruguay: 'Uruguay',
  Guyana: 'Guyana',
  Suriname: 'Suriname',

  // Châu Phi
  'South Africa': 'Nam Phi',
  Egypt: 'Ai Cập',
  Libya: 'Libya',
  Tunisia: 'Tunisia',
  Algeria: 'Algeria',
  Morocco: 'Morocco',
  Sudan: 'Sudan',
  'South Sudan': 'Nam Sudan',
  Ethiopia: 'Ethiopia',
  Eritrea: 'Eritrea',
  Djibouti: 'Djibouti',
  Somalia: 'Somalia',
  Kenya: 'Kenya',
  Uganda: 'Uganda',
  Tanzania: 'Tanzania',
  Rwanda: 'Rwanda',
  Burundi: 'Burundi',
  'Democratic Republic of the Congo': 'Cộng hòa Dân chủ Congo',
  'Republic of the Congo': 'Cộng hòa Congo',
  'Central African Republic': 'Cộng hòa Trung Phi',
  Cameroon: 'Cameroon',
  Chad: 'Chad',
  Niger: 'Niger',
  Nigeria: 'Nigeria',
  Benin: 'Benin',
  Togo: 'Togo',
  Ghana: 'Ghana',
  'Burkina Faso': 'Burkina Faso',
  Mali: 'Mali',
  Senegal: 'Senegal',
  Gambia: 'Gambia',
  'Guinea-Bissau': 'Guinea-Bissau',
  Guinea: 'Guinea',
  'Sierra Leone': 'Sierra Leone',
  Liberia: 'Liberia',
  'Ivory Coast': 'Bờ Biển Ngà',
  Mauritania: 'Mauritania',
  'Western Sahara': 'Tây Sahara',
  'Cape Verde': 'Cape Verde',
  'São Tomé and Príncipe': 'São Tomé và Príncipe',
  'Equatorial Guinea': 'Guinea Xích Đạo',
  Gabon: 'Gabon',
  Angola: 'Angola',
  Zambia: 'Zambia',
  Zimbabwe: 'Zimbabwe',
  Botswana: 'Botswana',
  Namibia: 'Namibia',
  Lesotho: 'Lesotho',
  Eswatini: 'Eswatini',
  Madagascar: 'Madagascar',
  Mauritius: 'Mauritius',
  Seychelles: 'Seychelles',
  Comoros: 'Comoros',
  Malawi: 'Malawi',
  Mozambique: 'Mozambique',

  // Châu Đại Dương
  Australia: 'Úc',
  'New Zealand': 'New Zealand',
  'Papua New Guinea': 'Papua New Guinea',
  Fiji: 'Fiji',
  'Solomon Islands': 'Quần đảo Solomon',
  Vanuatu: 'Vanuatu',
  Samoa: 'Samoa',
  Tonga: 'Tonga',
  Tuvalu: 'Tuvalu',
  Kiribati: 'Kiribati',
  Nauru: 'Nauru',
  Palau: 'Palau',
  'Marshall Islands': 'Quần đảo Marshall',
  Micronesia: 'Micronesia',
  'Cook Islands': 'Quần đảo Cook',
  Niue: 'Niue',

  // Một số tên đặc biệt khác
  'Republic of Korea': 'Hàn Quốc',
  "Democratic People's Republic of Korea": 'Triều Tiên',
  'Republic of China': 'Đài Loan',
  'Hong Kong': 'Hồng Kông',
  Macau: 'Ma Cao',
  Taiwan: 'Đài Loan',
  'Palestine, State of': 'Palestine',
  'Brunei Darussalam': 'Brunei',
  'Lao PDR': 'Lào',
  "Lao People's Democratic Republic": 'Lào',
  'United States of America': 'Hoa Kỳ',
  'Russian Federation': 'Nga',
  'Islamic Republic of Iran': 'Iran',
  'Kingdom of Saudi Arabia': 'Ả Rập Saudi',
  'Federal Republic of Germany': 'Đức',
  'French Republic': 'Pháp',
  'Italian Republic': 'Ý',
  'Kingdom of Spain': 'Tây Ban Nha',
  'Portuguese Republic': 'Bồ Đào Nha',
  'United Kingdom of Great Britain and Northern Ireland': 'Vương quốc Anh',
  'Republic of India': 'Ấn Độ',
  "People's Republic of China": 'Trung Quốc',
  'Socialist Republic of Vietnam': 'Việt Nam',
  'Commonwealth of Australia': 'Úc',
  'Federative Republic of Brazil': 'Brazil',
  'Argentine Republic': 'Argentina',
  'Republic of South Africa': 'Nam Phi',
  'Arab Republic of Egypt': 'Ai Cập',
};

// Hàm helper để dịch tên quốc gia
export const getVietnameseName = englishName => {
  if (!englishName) return '';

  // Tìm exact match trước
  if (COUNTRY_NAMES_VI[englishName]) {
    return COUNTRY_NAMES_VI[englishName];
  }

  // Thử tìm partial match (case-insensitive)
  const lowerEnglishName = englishName.toLowerCase();
  for (const [eng, vi] of Object.entries(COUNTRY_NAMES_VI)) {
    if (eng.toLowerCase() === lowerEnglishName) {
      return vi;
    }
  }

  // Nếu không tìm thấy, trả về tên gốc
  return englishName;
};

// Hàm để dịch region names
export const REGION_NAMES_VI = {
  Africa: 'Châu Phi',
  Americas: 'Châu Mỹ',
  Asia: 'Châu Á',
  Europe: 'Châu Âu',
  Oceania: 'Châu Đại Dương',
  Antarctic: 'Nam Cực',
};

export const getVietnameseRegion = englishRegion => {
  return REGION_NAMES_VI[englishRegion] || englishRegion;
};
